on:
  push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
        fail-fast: false
        matrix:
          config:
            - {os: windows-latest, r: 'release'}
            - {os: macOS-latest, r: 'release'}
            - {os: ubuntu-latest, r: 'release'}
    steps:
      - name: Checkout repo contents
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda:true

      - name: Create Conda env
      - run: conda env create -f environment.yml

      - name: Activate Conda and run tests
        shell: bash -l {0}
        run: |
          source activate mzsql
          python unit_tests.py
